[package]
name = “gpio_blinker”
Version = "0.1.0"
authors = “Eric Lockman eric@xealstudios.com”
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
sysfs_gpio = "0.6"
